### PR TITLE
Massive overhaul of JOSM Atlas plugin

### PR DESCRIPTION
**Pull request by don-vip**
Hello,
I have made a massive overhaul of JOSM Atlas plugin, in this PR.
It allows to load, render, select, search Atlas primitives without converting them to `OsmPrimitive`. This way it reduces the consumed memory (although I did not check how much: I would be curious to know that).
I made other changes to improve the UI:
- the relation dialog is filled and usable
- the JOSM history button, shortcut and menu entry are usable. So I deleted the Atlas history button (not needed anymore)
- various actions in standard JOSM dialogs are now usable (too many to list them exhaustively).

As it required a lot of changes in JOSM core to achieve this, the latest and greatest version of JOSM is required.

I would welcome feedback on this PR :)
Cheers,
Vincent

### CODE REVIEW

**Review by matthieun — APPROVED** [review]
Looks great! Thanks @don-vip

**Comment by hallahan** [comment]
Thanks for doing all of this work. I'll take a deeper look this week.

I know a lot of this work was in the core JOSM. Has everything been integrated and released in the latest version at this point?

**Comment by don-vip** [comment]
The latest required change is [13957](https://josm.openstreetmap.de/changeset/13957/josm/) to make the relation dialog usable. I did it two hours ago so the change is only available in "latest", not in "tested". The release of next tested version is expected at the end of this month (around 30 June). You can still test the plugin by running `gradlew runJosm`, it will launch JOSM 13957 :)

**Comment by hallahan** [comment]
Great, sounds good!

**Comment by hallahan** [comment]
Looks like Travis is failing. Could you try doing a `./gradlew spotlessApply` ?

**Pull request merged**
